-- 操作日志表
CREATE TABLE IF NOT EXISTS `operation_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` BIGINT DEFAULT NULL COMMENT '操作用户ID',
    `username` VARCHAR(100) DEFAULT NULL COMMENT '操作用户名',
    `user_role` INT DEFAULT NULL COMMENT '用户角色（1:一级管理员, 2:二级管理员, 3:普通用户）',
    `user_farm_id` BIGINT DEFAULT NULL COMMENT '用户所属单位ID',
    `user_farm_name` VARCHAR(200) DEFAULT NULL COMMENT '用户所属单位名称',
    `operation_type` VARCHAR(50) DEFAULT NULL COMMENT '操作类型（LOGIN, LOGOUT, CREATE, UPDATE, DELETE, VIEW等）',
    `module` VARCHAR(50) DEFAULT NULL COMMENT '操作模块（USER, DATASET, MODEL, TASK等）',
    `description` VARCHAR(500) DEFAULT NULL COMMENT '操作描述',
    `request_method` VARCHAR(10) DEFAULT NULL COMMENT '请求方法（GET, POST, PUT, DELETE）',
    `request_uri` VARCHAR(500) DEFAULT NULL COMMENT '请求URI',
    `request_params` TEXT DEFAULT NULL COMMENT '请求参数（JSON格式）',
    `response_status` INT DEFAULT NULL COMMENT '响应状态码',
    `response_time` BIGINT DEFAULT NULL COMMENT '响应时间（毫秒）',
    `ip_address` VARCHAR(50) DEFAULT NULL COMMENT '客户端IP地址',
    `user_agent` VARCHAR(500) DEFAULT NULL COMMENT '浏览器信息',
    `result` VARCHAR(20) DEFAULT NULL COMMENT '操作结果（SUCCESS, FAILURE）',
    `error_message` TEXT DEFAULT NULL COMMENT '错误信息',
    `log_date` VARCHAR(10) DEFAULT NULL COMMENT '日志日期（yyyy-MM-dd）',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_user_role` (`user_role`),
    INDEX `idx_user_farm_id` (`user_farm_id`),
    INDEX `idx_operation_type` (`operation_type`),
    INDEX `idx_module` (`module`),
    INDEX `idx_result` (`result`),
    INDEX `idx_log_date` (`log_date`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志表';
